spring:
  # jackson 配置，处理时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=root&useUnicode=true
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081
